apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-nginx

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image }}:{{ .values.image.tag }}"  #result will be image name & the tag which we nemtioned in values.yaml file eg: "nginx:1.26"
          
          #image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}" #wehn we use "default", result will be if the image tag is not mentioned in values.yaml file the iamge tag          #will be "latest" eg: "nginx:latest"
          
          port: 
            containerPort: "{{ .Values.port }}"   #this can be used when there is only one port ,

            #suppose you want to expose multiple port like 80, 22, 443  then we can go with "range " that is shown below
            #
            #
            #ports:
            #"{{- range .Values.ports}}
            #   - containerPort: {{.}}
            # {{- end }}
          

